version: "3"
services:
    fast-kafka-api-devel:
        image: ghcr.io/airtai/nbdev-mkdocs
        hostname: $DOCKER_COMPOSE_PROJECT-devel
        container_name: $DOCKER_COMPOSE_PROJECT-devel
        ports:
            - "8888:8888"
            - "4000:4000"
        networks:
            - fast-kafka-api-network
        volumes:
            - $AIRT_PROJECT:/work/fast-kafka-api
            - /etc/passwd:/etc/passwd
            - /etc/group:/etc/group
            - /etc/shadow:/etc/shadow
            - $HOME/.ssh:$HOME/.ssh
            - $HOME/.gitconfig:/root/.gitconfig
        environment:
            KAFKA_HOSTNAME: $KAFKA_HOSTNAME
            KAFKA_PORT: 9092
            USER: $USER
            USERNAME: $USERNAME
            PRESERVE_ENVS: $PRESERVE_ENVS
        depends_on:
            kafka:
                condition: service_healthy

networks:
    fast-kafka-api-network:
        name: "${USER}-fast-kafka-api-network"
